### ISSUE TITLE
Exception in Thread-8 in deepRanking.py

### ISSUE THREAD

**Issue by Purvak-L** [akarshzingade/image-similarity-deep-ranking#31]
Hi,
I'm getting this error while running deepRanking.py. Any help of why this is the case?
Also, all I did was pass query_and_triplets.txt file to deepRanking.py. Am I doing it correctly?

Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\Purvak\Anaconda3\envs\py35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\Purvak\Anaconda3\envs\py35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Purvak\Anaconda3\envs\py35\lib\site-packages\keras\utils\data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
  File "C:\Users\Purvak\Documents\IRDS\ImageDataGeneratorCustom.py", line 721, in __next__
    return self.next(*args, **kwargs)
  File "C:\Users\Purvak\Documents\IRDS\ImageDataGeneratorCustom.py", line 1023, in next
    fname = self.filenames[j]
IndexError: list index out of range

Traceback (most recent call last):
  File "deepranking.py", line 129, in <module>
    epochs=5
  File "C:\Users\Purvak\Anaconda3\envs\py35\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Purvak\Anaconda3\envs\py35\lib\site-packages\keras\engine\training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
StopIteration

**Comment by harshsp31** [comment]
I'm getting the same issue. Did anybody find a solution?

**Comment by YXWisaboy** [comment]
Please make sure the data volume is a multiple of 8（24/3）

**Comment by mayankdevedw** [comment]
Did you find solution of this? My data volume is multiple of 8 only, number of triplets are 5016
